# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Base info
mc_version=26.1.1
neo_version=26.1.1.11-beta
mod_group=com.mrbysco.resourcepandas
mod_id=resourcepandas
mod_archive_name=Resource-Pandas

#Publishing
mod_name=Resource Pandas
curseforge_id=410681
modrinth_id=aQkicaUD

# Version
version=10.0.0

# Mod support
jei_minecraft=26.1.1
jei_version=29.4.0.23
#rei_version=21.11.814
#architectury_version=19.0.1
#cloth_config_version=19.0.147
#crafttweaker_version=21.11.153
jade_id=7886513